version: 2

defaults:
  workspace_root: &workspace_root
    ~/isogeo-help

  nodejs_container: &nodejs_container
    working_directory: *workspace_root
    docker:
      - image: circleci/node:8-stretch

  filters: &default_filters
    tags:
      only: '/v[0-9]+(\.[0-9]+)*/'

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_node_modules: &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - isogeo-help-node-{{ checksum "yarn.lock" }}
        - isogeo-help-

jobs:
  checkout:
    <<: *nodejs_container
    steps:
      - checkout

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./

  install:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - restore_cache:
          name: Restore yarn cache
          keys:
            - isogeo-help-yarn-{{ checksum "yarn.lock" }}
            - isogeo-help-yarn-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          name: Save yarn cache
          key: isogeo-help-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn/

      - save_cache:
          name: Save node_modules cache
          key: isogeo-help-node-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

  build:
    <<: *nodejs_container
    steps:
      - *attach_workspace
      - *restore_node_modules

      - run:
          name: Set latest gitbook alias
          command: yarn gitbook alias node_modules/gitbook latest

      - run:
          name: Build output bundles
          command: yarn gitbook build Help/ dist/

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - dist/

  deploy:
    <<: *nodejs_container
    steps:
      - *attach_workspace

      - run:
          name: Install rclone
          command: sudo apt-get install rclone

      - deploy:
          name: Upload to Azure Blob Storage
          command: rclone sync dist/ azure:\$web --delete-after

workflows:
  version: 2

  push:
    jobs:
      - checkout:
          filters: *default_filters

      - install:
          requires:
            - checkout
          filters: *default_filters

      - build:
          requires:
            - install
          filters: *default_filters

      - deploy:
          requires:
            - build
          filters: *default_filters
            # <<: *default_filters
            # branches:
            #   ignore: /.*/